# Generated by Django 3.2.8 on 2021-11-12 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya')),
                ('status', models.BooleanField(choices=[(False, "✖️ O'chirilgan"), (True, '✅ Faol')], default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('description', models.TextField(max_length=1000, verbose_name='Tavsifi')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegra.ph havola')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)], verbose_name='Narxi')),
                ('currency', models.CharField(choices=[("so'm", "So'm"), ('$', 'Dollar')], default="so'm", max_length=5, verbose_name='Valyuta')),
                ('image', models.ImageField(upload_to='images', verbose_name='Maxsulot rasmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Bot.category')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID User')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='@username')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name in Telegram')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Is Registered')),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha")], max_length=100, null=True, verbose_name='Language')),
                ('product_cart', models.ManyToManyField(to='Bot.Product')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Buyurtma raqami')),
                ('total_cost', models.IntegerField(verbose_name='Narxi')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Sanasi')),
                ('address_location', models.TextField(max_length=10000, verbose_name='Manzili')),
                ('ordered_products', models.ManyToManyField(to='Bot.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Bot.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
